/**
 * Laravel Generator APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Alerta { 
    /**
     * id
     */
    id?: number;
    /**
     * content
     */
    content: string;
    /**
     * url
     */
    url: string;
    /**
     * user_id
     */
    user_id: number;
    /**
     * actual
     */
    actual: boolean;
    /**
     * documento_id
     */
    documento_id?: number;
}

