/**
 * Laravel Generator APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Certificado { 
    /**
     * id
     */
    id?: number;
    /**
     * user_id
     */
    user_id: number;
    /**
     * version
     */
    version: number;
    /**
     * autor
     */
    autor: string;
    /**
     * titulo
     */
    titulo: string;
    /**
     * contenido
     */
    contenido: string;
    /**
     * uuid
     */
    uuid: string;
    /**
     * red
     */
    red: string;
    /**
     * traza
     */
    traza: string;
    /**
     * ipfs
     */
    ipfs: string;
    /**
     * clave
     */
    clave?: string;
    /**
     * bloqueado
     */
    bloqueado: boolean;
    /**
     * created_at
     */
    created_at?: string;
    /**
     * updated_at
     */
    updated_at?: string;
}

